### ISSUE TITLE
GUI second version

### ISSUE THREAD

**Issue by Gabighz** [Gabighz/Digital-Aristotle#7]
To the chatbox:

- <del>An 'Enter' button</del>

- <s>Keep input/output text in the chatbox as chat logs</s>

- <s>The ability to scroll through the chat logs</s>

- <s>Ability to clear conversation display</s>

**Comment by AviVarma** [comment]
Have done some research on how other bots work and possible ways to store the chat data, will be analysing the code and trying to implement some of the ideas soon.

**Comment by AviVarma** [comment]
I looked into chat services that were made on php since i thought it was and issue in the web page itself. when i tired to implement it there seems to just be too much difference in the architecture. Note what we are missing is a log.html which stores the previous chat data. Could the messages array be the substitute in scrip.js?

**Comment by Gabighz** [comment]
Yes, the array called "messages" does just that. We need to figure out how to use it properly.

**Comment by AviVarma** [comment]
I might have found a breakthrough, a design for a classic IRC chat system uses a log.html which stores all of the users inputs. the log is then printed onto the screen to show the chat-log resulting in the entire history to be show. i will be trying to implement this, since the JavaScript's array doesn't seem to be working.
